# Standard ROS 2 message header
std_msgs/Header header

# each value rapresent the voltage 
float32 pot_pedal_a
float32 pot_pedal_b
float32 pot_throttle_valve_a
float32 pot_throttle_valve_b

uint16 temp_oil
uint16 temp_engine
uint16 temp_intake
uint16 temp_ambient

uint16 nmot
float32 vehicle_speed
uint16 gear
float32 throttle

float32 p_oil
float32 p_fuel
float32 p_intake
float32 p_ambient

float32 battery_voltage
float32 accelerator_pedal
float32 fan_control

float32 clutch_percentage
float32 steering_angle
uint32 checksum_steering_angle
float32 wheel_angle

float32 wheel_speed_front_left
float32 wheel_speed_front_right
float32 wheel_speed_rear_left
float32 wheel_speed_rear_right

float32 p_brake_rear 
float32 p_brake_front
float32 error_throttle
float32 error_pedal

float32 p_ebs_1
float32 p_ebs_2

uint8 bool_ack_ideal_launch_control
uint8 bool_ack_real_launch_control

