/control_node:
  ros__parameters:
    tick_interval: 50 # Milliseconds. (Estimation -> control -> actuation) loop interval
    wcet_ns: 5000000 # 5ms

    estimation:
      type: Noop
      params:
        odometry_topic: "/Odometry"

    # Launch and stop procedure (start by engaging clutch - end by disengaging clutch, braking, sending stop message, etc..)
    launch_and_stop:
      enabled: true # Disable this on the sim or when you're using the HUMAN POWERTRAIN
      stop_on_lap: 12 # Stop when lap counter publishes this lap
      launch_throttle: 0.2 # Constant throttle applied while releasing clutch
      max_launch_duration: 1.5 # Maximum time to wait for the clutch to be released before starting

    control:
      type: PurePursuit2023
      params:
        minLookForward: 5.0
        minLookForwardGain: 0.4
        steerGain: 1.0
        targetVelocity: 3.33 # This gets overwritten after current lap > dynamicTargetSpeed.slowLaps if dynamicTargetSpeed.enabled is true!

        dynamicTargetSpeed:
          enabled: true # If this is false, then targetVelocity is used.
          slowLaps: 1
          minSpeedDistance: 5
          k_smooth: 0.1
          minSpeed: 3.33
          maxSpeed: 8.0
          targetSpeedWeight:  0.85
          velocityCoeffs: [0.5051, 1.063, -0.02495, 0.0003832, -3.251e-6, 1.494e-8, -3.511e-11, 3.32e-14]


    # Actuation settings
    actuation:
      actuators:
        0:
          enabled: true
          type: CANOpenBridge
          params:
            steer_topic: "/command/steer"
            brake_topic: "/command/brake"
            clutch_topic: "/command/clutch"

        1:
          enabled: true
          type: Sim
          params:
            topic: "/sim/drive_parameters"
        
        2:
          enabled: false
          type: spi_apps
          params:
            dev: "/dev/ur_mom"

    # Reference path settings
    reference_path_manager:
      # Reference path sources in order of priority, 0 is highest
      # Whenever a path from a higher priority source is received, any lower priority source is destroyed
      sources:
        0:
          enabled: false
          type: "ROS_SpeedProfilePoints"
          params:
            topic: "/planning/global"
            is_closed: true

        1:
          enabled: true
          type: "ROS_Marker"
          params:
            topic: "/planning/center_line_completed"
            is_closed: true
            qos_override:
              durability: transient_local
              reliability: reliable

        2:
          enabled: true
          type: "ROS_Marker"
          params:
            topic: "/planning/center_line"
            is_closed: false

    vehicle_parameters:
      wheelbase: 1.541 # distance between front and rear axle [m]
      lr: 0.75 # distance between CoM and rear axle [m]
      max_steering_angle: 0.3979351 # maximum angle at the wheel [rad]
    
    viz:
      enabled: true
      topic: "/control/viz"
      min_interval_ms: 100

    start_stop:
      lapTarget: 10
      brakeToStop: 8.0
      timeForLaunch: 1.0

    inspection:
      velocityMultiplier: 1.0      