/mmr_data_logger_node:
  ros__parameters:
    generic:
      debug: true
      WCET: 5000000 # ms
      period: 10000000 # 10ms
      deadline: 10000000
    topics:
      statusActuatorTopic: "/actuator/status" 
      ecuStatusTopic: "/status/ecu"
      xsenseTopic: "/imu/data"
      asTopic: "/as/status"
      missionTopic: "/mission/selected"
      lapCounterTopic: "planning/race_status"
      conesActualTopic: "/perception/cones"
      conesAllTopic: "/slam/cones_positions"
      controlTopic: "/control/log"