/canbus_bridge_node:
  ros__parameters:
    generic:
      interface: can0
      bitrate: 1000000
      debug: true
      WCET: 5000000 # 5ms
      period: 10000000 # 10ms
      deadline: 10000000
      max_msgs: 25
      control_freq_div: 1
    topic:
      cmdEcuTopic: "/command/ecu"
      ecuStatusTopic: "/status/ecu"
      resStatusTopic: "/status/res"
      ActuatorsStatusTopic: "/actuator/status"
      missionSelectTopic: "/mission/selected"
      outputImuTopic: "/canbus/imu/data"
      controlLogTopic: "/control/log"
      raceStatusTopic: "/planning/race_status"
    gear:
      ctrLimit: 5
      changeDeltaTime: 500 #ms
      delayCmdEcu: 1 #ms
    launch_control:
      ctrLimit: 2
      changeDeltaTime: 500 #ms
      delayCmdEcu: 50 #ms
    neutral:
      ctrLimit: 2
      changeDeltaTime: 500 #ms
      delayCmdEcu: 50 #ms